### ISSUE TITLE
line 24 in CameraDevice.h

### ISSUE THREAD

**Issue by Algomorph** [arpg/HAL#110]
line 24 in CameraDevice.h that sets m_cam was commented out in  4dcb4ef, which causes segfaults and bad karma...

**Comment by crheckman** [comment]
Could have been avoided by using a hal::uri rather than an std::string, but there's no necessity for this constructor to be unavailable. I have removed the comment notes.

**Comment by Algomorph** [comment]
Thanks. SensorViewer in arpg_apps uses that constructor, along with other ARPG apps, so, for now it's necessary.
