### ISSUE TITLE
Possible bug in OpenCVDriver

### ISSUE THREAD

**Issue by Algomorph** [arpg/HAL#117]
Here is a code excerpt from ```OpenCVDriver::Capture()```:
```C++
  // This may not store the image in contiguous memory which PbMsgs
  // requires, so we might need to copy it
  cv::Mat cv_image;
  if(force_greyscale_) {
    cvtColor(temp, cv_image, CV_RGB2GRAY);
  } else if (!cv_image.isContinuous()) {
    temp.copyTo(cv_image);
  } else {
    cv_image = temp;
  }
```

Shouldn't this be
```C++
 } else if (!temp.isContinuous()) {
```
, since we want to check the block of memory pointed to by temp, not the new cv_image cv::Mat?
I believe this is causing crashes in some of my client applications on random matrices which disappear when I explicitly copy the matrix before operating on it.

**Comment by crheckman** [comment]
Good catch. I've tested and it looks good so it's been pushed to master in 2b0d58c.
