### ISSUE TITLE
Orbbec camera unsupported

### ISSUE THREAD

**Issue by crheckman** [arpg/HAL#136]
@mcguire-steve please document your magic to make this work on Linux here (in as simple as terms as possible so I can translate it to Mac world).

Thanks!

**Comment by mcguire-steve** [comment]
On linux:
There is a set of binaries under the ros_astra_camera/include/openni2_redist that include the OpenNI2 plugins and ini files for a variety of architectures - but not OSX. Copying this plugin to the system OpenNI2 plugins dir allows NiViewer and HAL openni2:// drivers to access the Orbbec, once appropriate UDev rules are added as well to grant user-space permissions via libusb to the Orbbec VID/PID. I don't remember where I downloaded the ROS package with the binaries - it's not under source control. Trying to find that now.

**Comment by mcguire-steve** [comment]
Under the Mac OSX download link: http://dl.orbbec3d.com/dist/astra/0.5.0/AstraSDK-0.5.0-darwin-x64.tar.gz

there is a subdir: /AstraSDK-0.5.0-20160426T102621Z-darwin-x64/lib/Plugins/openni2/OpenNI2/Drivers/

that contains the binaries that should allow an OpenNI2 application (the HAL driver, NiViewer) to access the Orbbec. (liborbbec.dylib , libusb, and the ini file)

**Comment by mcguire-steve** [comment]
In the Linux SDK, the corresponding files are under /OpenNI-Linux-x64-2.2/Redist/OpenNI2/Drivers/

It appears that Orbbec has not released the necessary build files for this particular libORBEC.so. However, by fussing with their git repo, I was able to build the necessary plugin - but it doesn't quite work.

**Comment by crheckman** [comment]
Thanks, @mcguire-steve!
