### ISSUE TITLE
HAL not building with latest version of libfreenect

### ISSUE THREAD

**Issue by Algomorph** [arpg/HAL#82]
This was discussed somewhat earlier in [this vicalib issue](https://github.com/arpg/vicalib/issues/21).  See second post there for comparison of depth feed quality.

Unfortunately, HAL doesn't build with the latest version of freenect2 from [OpenKinect](https://github.com/OpenKinect/libfreenect2). 
```
Freenect2Driver.h:9:45: fatal error: libfreenect2/depth_registration.h: No such file or directory
 #include <libfreenect2/depth_registration.h>
```
The depth_registration header doesn't exist anymore. I've began looking into this a little deeper, will try to address it tomorrow, but no guarantees or even tentative schedule. Please let me know if you're planning to look into this.

**Comment by gsibley** [comment]
Excellent -- this hasn't been brought up yet.  It'd be wonderful if you
could tackle it.

On Thu, Apr 30, 2015 at 2:55 PM, Gregory Kramida <notifications@github.com>
wrote:

> This was discussed somewhat earlier in this vicalib issue
> <https://github.com/arpg/vicalib/issues/21>.
>
> Unfortunately, HAL doesn't build with the latest version of freenect2 from
> OpenKinect <https://github.com/OpenKinect/libfreenect2>.
>
> Freenect2Driver.h:9:45: fatal error: libfreenect2/depth_registration.h: No such file or directory
>  #include <libfreenect2/depth_registration.h>
>
> The depth_registration header doesn't exist anymore. I've began looking
> into this a little deeper, will try to address it tomorrow, but no
> guarantees or even tentative schedule. Please let me know if you're
> planning to look into this.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/arpg/HAL/issues/82>.
>



-- 
Gabe Sibley, PhD

Assistant Professor
Department of Computer Science
University of Colorado, Boulder
--

**Comment by Algomorph** [comment]
The libfreenect2/depth_registration.h headers provide routines for registration of depth feed to the RGB feed.
In the new freenect2 version, there now exists a registration.h header, which provides the same routines.
I could just change the code in the HAL Freenect2 driver to use registration.h, however, I foresee a problem with this: depth registration provided by luma in (commit cfd431f90f )[https://github.com/dorian3d/libfreenect2/commit/cfd431f90fabfe0cdfa13d4991991c6086a83107] includes an opencl version, which, I'm assuming is used by the driver and is (probably) much faster than the CPU-only code provided by the upstream OpenKinect/libfreenect2.

The ideal solution would be to (1) adapt the HAL driver code to use the registration.h header, (2) fork the upstream libfreenect, modify the registration.h & add appropriate registration.cl to the upstream trunk via a pull request, and, until the pull request is tested/accepted, pull freenect2 from the new fork. I'll see what I can do, but, as usual, no promises. If anyone wants to tackle any of the {a,b}, that would be great, just let me know, please.
