### ISSUE TITLE
install directory problem for out-of-source builds

### ISSUE THREAD

**Issue by Algomorph** [arpg/HAL#85]
CMake source dir: <something>/HAL
CMake binary dir: <something>/builds/HAL

```sudo make install``` or checkinstall yields:
```
-- Installing: /usr/local/include/../../HAL/HAL/Devices/DeviceException.h
-- Installing: /usr/local/include/../../HAL/HAL/Devices/DeviceFactory.h
-- Installing: /usr/local/include/../../HAL/HAL/Devices/DeviceRegistry.h
```
(Which all actually end up in /usr/HAL/)

This breaks vicalib.

**Comment by crheckman** [comment]
yeesh... thank goodness for `make uninstall` huh?

could you test #86 please?

**Comment by Algomorph** [comment]
The fix worked for me. Closing.
