### ISSUE TITLE
Pose.h include incorrect

### ISSUE THREAD

**Issue by Algomorph** [arpg/HAL#90]
In Pose.h,
```C++
#include "Messages.pb.h"
``` 
should be 
```C++
#include <HAL/Messages.pb.h>
```

I cannot create a pull request, sorry: you've closed the pull request I had for the latest freenect2 driver fix, but that's the only one that works right now with latest freenect2 (see #88, #63). We're still using that, and I'm not sure how to make two forks from the same origin.

**Comment by Algomorph** [comment]
P.S. Oh, I guess I could create a branch on my fork, regressing a few commits. Didn't think of it.

**Comment by Algomorph** [comment]
The Messages.pb.h header does not resolve otherwise when trying to build anything that uses Pose.h.

**Comment by crheckman** [comment]
I don't know if we have anything in our repos that uses Pose.h explicitly right now so it's likely that was the culprit. Thanks for letting us know! #91 (now merged to master) should resolve it; if so, feel free to close this Issue.

More comments on the way on other issues.

**Comment by Algomorph** [comment]
D-MoCap does. See arpg/D-MoCap#1. Upgrading HAL at this point I think breaks vicalib for us, so I can't really pull HAL to test the D-MoCap modifications properly just yet. Methinks now they should (??) compile on your end, though. I'll close this one for now. Thanks!

**Comment by crheckman** [comment]
I'll consult with @gsibley on how we want to support D-MoCap since @dorian3d was the primary on it previously.
