### ISSUE TITLE
RealSense driver broken

### ISSUE THREAD

**Issue by Algomorph** [arpg/HAL#92]
We earlier misattributed this problem to the align driver (see post by @artforlife in #63).
I looked into it deeper today, it had nothing to do with the proposed align driver.

The problem has to do with RealSense driver containing its own version of UVC driver.
I got the *libuvc_ex*/libuvc_config.h to generate in the build folder., tried fixing it somehow by correcting folder structure, adding the missing include directories, removing the extra sources for the driver project, changing pb namespace to hal in driver sources.

However, even after compilation errors were resolved, the linker had run into conflict with the existing version of UVC. I gave up, made a hard reset, and built HAL without RealSense (we're not using it).

I propose this immediate change: do not build the broken RealSense by default.

I do not know why the RealSense driver requires its own version. If there are no differences between that and the official UVC driver, I propose this long-term fix: remove the extra version of UVC from the RealSense driver. Instead, have it check for BUILD_UVC in the parent scope and use the offical HAL UVC driver. If BUILD_UVC is not set while BUILD_RealSense is set, throw a fatal CMake error.

**Comment by crheckman** [comment]
Thanks for your investigation. The temporary fix has been merged in #94 and we'll pursue the long-term fix in #93 beginning of June.
